### ISSUE TITLE
How to Print Multiple Arraylist?

### ISSUE THREAD

**Issue by lionheart83** [sanxy/BluetoothPrinter#2]
Sir, i need some help! How to print an Arraylist like Recyclerview? Any additional code? Thx

**Comment by sanxy** [comment]
What you need to do is use a for loop to loop through you list and print each line details. Simply put the print function in the for loop where you get you details.
You can also read the Part Two [here](https://medium.com/@folahan/how-to-print-from-android-devices-using-thermal-bluetooth-printer-part-two-6418ba9469ac)
